### ISSUE TITLE
About first show with input "q".

### ISSUE THREAD

**Issue by zxdposter** [danielecook/Quiver-alfred#4]
![wechatimg27](https://cloud.githubusercontent.com/assets/13846260/24588387/84e49ec6-17f9-11e7-91ee-a29bc00bea1f.jpeg)

```
Starting debug for 'Quiver Search'

[2017-04-02 23:10:58][ERROR: input.scriptfilter] Code 1: 23:10:58 workflow.py:1692 DEBUG    Data `library_location` stored in `cpickle` format
23:10:58 workflow.py:1707 DEBUG    Stored data loaded from : /Users/zxd/Library/Application Support/Alfred 3/Workflow Data/com.cook.quiver/library_location.cpickle
23:10:58 workflow.py:1839 DEBUG    Cached data saved at : /Users/zxd/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.cook.quiver/update_db.cpickle
23:10:58 workflow.py:1692 DEBUG    Data `library_location` stored in `cpickle` format
23:10:58 workflow.py:1707 DEBUG    Stored data loaded from : /Users/zxd/Library/Application Support/Alfred 3/Workflow Data/com.cook.quiver/library_location.cpickle
23:10:58 workflow.py:2185 ERROR    'Inbox'
Traceback (most recent call last):
  File "/Users/zxd/Documents/Alfred/Alfred.alfredpreferences/workflows/user.workflow.889ADE16-224B-466A-AE7D-07941B090861/workflow/workflow.py", line 2178, in run
    func(self)
  File "run.py", line 110, in main
    wf.add_item(notebooks_q[n]["notebook"], str(notebooks_q[n]["count"]) + " item(s)", autocomplete = n, icon = icon)
KeyError: 'Inbox'
23:10:58 workflow.py:2205 DEBUG    Workflow finished in 0.002 seconds.
```

**Comment by danielecook** [comment]
Hmmm - i'm not really sure what is going on here. Are there any notes in your inbox?

**Comment by zxdposter** [comment]
@danielecook No I haven't. By the way, I am using alfred3.

<img width="217" alt="wx20170406-000659 2x" src="https://cloud.githubusercontent.com/assets/13846260/24715100/fcf365cc-1a5c-11e7-947d-3f3f2fb50502.png">

**Comment by danielecook** [comment]
Try creating a note in your inbox and see if that resolves it. I'll try to get around to fixing the bug.

Thanks,
Dan

**Comment by xinnyu** [comment]
I got the same error.

**Comment by zxdposter** [comment]
Yes, create a note in inbox is did resolves.

**Comment by danielecook** [comment]
This is resolved.
